export async function onRequest({ env }) {
    const WEBRTC_PLAYBACK_URL_FROM_YOUR_LIVE_INPUT = env.WEBRTC_PLAYBACK_URL_FROM_YOUR_LIVE_INPUT
    const WEBRTC_URL_FROM_YOUR_LIVE_INPUT = env.WEBRTC_URL_FROM_YOUR_LIVE_INPUT
    console.log('Test', WEBRTC_URL_FROM_YOUR_LIVE_INPUT)
    return console.log(WEBRTC_PLAYBACK_URL_FROM_YOUR_LIVE_INPUT, WEBRTC_URL_FROM_YOUR_LIVE_INPUT);
}