export async function onRequest({ env }) {
    const WEBRTC_PLAYBACK_URL_FROM_YOUR_LIVE_INPUT = env.WEBRTC_PLAYBACK_URL_FROM_YOUR_LIVE_INPUT
    const WEBRTC_URL_FROM_YOUR_LIVE_INPUT = env.WEBRTC_URL_FROM_YOUR_LIVE_INPUT
    return new Response(WEBRTC_URL_FROM_YOUR_LIVE_INPUT + WEBRTC_PLAYBACK_URL_FROM_YOUR_LIVE_INPUT);
}